# dev setup assumes a mock-api image is built from api-dockerfile
version: '2'
services:
  api:
    volumes:
      - ./server:/usr/src/app/server
    image: mock-api
  ui:
    build: .
    volumes:
      - ./dist:/usr/src/app/dist
    ports:
      - "80:80"
    depends_on:
      - api 
